### ISSUE TITLE
kernel error when I open a notebook with the simple-kernel-nashorn

### ISSUE THREAD

**Issue by nafaimmoune** [dpressel/simple-kernel-nashorn#1]
I try to clone the project, and when I open a notebokk with the new kernel (simple-kernel-nashorn) I get a kernel error with this issues 

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1512, in _execute
    result = yield result
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
 what's wrong?

**Comment by dpressel** [comment]
Are you able to run other kernels like the default ones?

**Comment by nafaimmoune** [comment]
I tried the python 3 kernel and it works

**Comment by dpressel** [comment]
I did update the gradle deps in the project, maybe that will help you.  Then I did the following steps:

```
 2301  git clone https://github.com/dpressel/simple-kernel-nashorn.git
 2302  cd simple-kernel-nashorn/
 2303  ./gradlew build && ./gradlew fatJar
 2304  ./install_script.sh 
 2305  jupyter-notebook 
```

And it runs just fine for me (see screencap)

![nashorn-kernel](https://user-images.githubusercontent.com/247881/48072105-ce336f00-e1a9-11e8-84ae-e8c626284a25.png)

**Comment by nafaimmoune** [comment]
you use which version of python?

**Comment by dpressel** [comment]
The kernel is not written in Python, it’s written in Java

**Comment by nafaimmoune** [comment]
yes I know that, but the version of jupyter notebook depends on the version of python no?

**Comment by nafaimmoune** [comment]
I'v resolved it. It works with version 2.7 phython and not with version 3.x. 
thank you

**Comment by dpressel** [comment]
Ok, glad to hear it worked for you. FWIW, I am running Jupyter 5.0.0 with Python 3.6
